(function(g){var window=this;var Xwa=function(a,b){var c=[];g.Ml(b,function(a){try{var b=g.wD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.vD(b)&&c.push(a):c.push(a)},a);
return c},Ywa=function(a,b){var c=Xwa(a,b);
(0,g.G)(c,function(a){g.wD.prototype.remove.call(this,a)},a)},B8=function(a,b){g.a1.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.V=a;this.F={};this.T(a,"onMdxReceiversChange",this.J);this.T(a,"presentingplayerstatechange",this.J);this.J()},Zwa=function(){var a=g.UG;
Ywa(a,a.g.Xd(!0))},C8=function(a){g.wH.call(this,"ScreenServiceProxy");
this.cd=a;this.o=[];this.o.push(this.cd.$_s("screenChange",(0,g.y)(this.xT,this)));this.o.push(this.cd.$_s("onlineScreenChange",(0,g.y)(this.JP,this)))},D8=function(a){g.jH("cloudview",a)},$wa=function(a){D8("setApiReady_ "+a);
g.qa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},E8=function(){return g.v("yt.mdx.remote.cloudview.instance_")},axa=function(a){g.lG[a]&&(a=g.lG[a],(0,g.G)(a,function(a){g.jG[a]&&delete g.jG[a]}),a.length=0)},F8=function(){return g.v("yt.mdx.remote.connection_")},G8=function(a){g.qa("yt.mdx.remote.connectData_",a,void 0)},bxa=function(a){g.qa("yt.mdx.remote.currentScreenId_",a,void 0)},H8=function(){return g.v("yt.mdx.remote.currentScreenId_")},J8=function(){if(!I8){var a=g.v("yt.mdx.remote.screenService_");
I8=a?new C8(a):null}return I8},K8=function(a){g.qa("yt.mdx.remote.cloudview.initializing_",a,void 0)},L8=function(){return!!g.v("yt.mdx.remote.cloudview.apiReady_")},M8=function(a){D8("setCastInstalled_ "+a);
g.WG("yt-remote-cast-installed",a)},N8=function(a){g.jH("cloudview",a)},cxa=function(a,b){E8().init(a,b)},O8=function(){return!!g.XG("yt-remote-cast-installed")},dxa=function(){D8("dispose");
var a=E8();a&&a.dispose();g.qa("yt.mdx.remote.cloudview.instance_",null,void 0);$wa(!1);g.nG(P8);P8.length=0},exa=function(){var a=window.document.createElement("a");
g.Gd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Sa(a)},fxa=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},gxa=function(a){var b=g.iG();
if(b)if(b.clear(a),a)axa(a);else for(var c in g.lG)axa(c)},Q8=function(a){return 0<=window.navigator.userAgent.indexOf(a)},R8=function(){return g.v("yt.mdx.remote.channelParams_")||{}},T8=function(a){var b=F8();
G8(null);a||bxa("");g.qa("yt.mdx.remote.connection_",a,void 0);S8&&((0,g.G)(S8,function(b){b(a)}),S8.length=0);
b&&!a?g.qG("yt-remote-connection-change",!1):!b&&a&&g.qG("yt-remote-connection-change",!0)},hxa=function(){return g.v("yt.mdx.remote.connectData_")},U8=function(){var a=H8();
if(!a)return null;var b=J8().fe();return g.vH(b,a)},ixa=function(a,b){M8(!0);
K8(!1);cxa(a,function(a){a?($wa(!0),g.oG("yt-remote-cast2-api-ready")):(N8("Failed to initialize cast API."),M8(!1),g.YG("yt-remote-cast-available"),g.YG("yt-remote-cast-receiver"),dxa());b(a)})},jxa=function(){return O8()?E8()?E8().getCastSession():(N8("getCastSelector: Cast is not initialized."),null):(N8("getCastSelector: Cast API is not installed!"),null)},kxa=function(){var a=exa(),b=window.document.getElementById(a),c=b&&g.yF(b,"loaded");
c||b&&!c||(b=fxa(a,function(){g.yF(b,"loaded")||(g.zF(b,"loaded","true"),g.oG(a),g.GE(g.za(gxa,a),0))}))},lxa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},mxa=function(){if(g.opa){var a=2,b=g.Eh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Jh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Gh,c)}},W8=function(a,b){H8();
U8()&&U8();bxa(a.id);var c=new g.BI(V8,a,R8());c.connect(b,hxa());c.subscribe("beforeDisconnect",function(a){g.qG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){F8()&&(F8(),T8(null))});
T8(c)},X8=function(){var a=g.DH();
if(!a)return null;var b=J8().fe();return g.vH(b,a)},Y8=function(a){g.jH("remote",a)},Z8=function(){var a=F8();
return!!a&&3!=a.getProxyState()},$8=function(){L8()?E8().stopSession():N8("stopSession called before API ready.");
var a=F8();a&&(a.disconnect(1),T8(null))},nxa=function(){var a=J8().cd.$_gos();
var b=U8();b&&F8()&&(g.uH(a,b)||a.push(b));return lxa(a)},b9=function(a,b){g.$F.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.KB;this.A=this.o=null;this.J=(0,g.y)(this.RN,this);this.F=(0,g.y)(this.fl,this);this.G=(0,g.y)(this.QN,this);this.K=(0,g.y)(this.eO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Yt,this),oxa(this))):c=3;0!=c&&(b?this.Yt(c):g.GE((0,g.y)(function(){this.Yt(c)},this),0));
var d=jxa();d&&a9(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},c9=function(a){return new g.qI(a.B.getPlayerContextData())},pxa=function(a,b,c,d,e){var f=c9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.uI(f,b,d);g.t(c)&&(g.sI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);d9(a,"setPlaylist",l);e||e9(a,f)},oxa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.aQ,a),this))},a)},qxa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},f9=function(a,b){50>a.C.Mc()&&g.MB(a.C,b)},g9=function(a,b,c){var d=c9(a);
g.sI(d,c);-1E3!=d.g&&(d.g=b);e9(a,d)},d9=function(a,b,c){a.B.sendMessage(b,c)},e9=function(a,b){qxa(a);
a.B.setPlayerContextData(g.vI(b));oxa(a)},a9=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.F),a.fl(null));
a.A=b;a.A&&(h9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.F),a.A.media.length&&a.fl(a.A.media[0]))},rxa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=c9(a);b.contentId!=d.videoId&&h9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.sI(d,a.o.getEstimatedTime());e9(a,d)}else h9("No cast media video. Ignoring state update.")},h9=function(a){g.jH("CP",a)},i9=function(a,b,c){return(0,g.y)(function(a){this.jc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.jc("Retrying "+b+" using MDx browser channel."),d9(this,b,c))},a)},sxa=function(a,b){var c=!1;
E8()||(c=new g.kI(a,b),c.subscribe("yt-remote-cast2-availability-change",function(a){g.WG("yt-remote-cast-available",a);g.qG("yt-remote-cast2-availability-change",a)}),c.subscribe("yt-remote-cast2-receiver-selected",function(a){D8("onReceiverSelected: "+a.friendlyName);
g.WG("yt-remote-cast-receiver",a);g.qG("yt-remote-cast2-receiver-selected",a)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(a){D8("onReceiverResumed: "+a.friendlyName);
g.WG("yt-remote-cast-receiver",a)}),c.subscribe("yt-remote-cast2-session-change",function(a){D8("onSessionChange: "+g.rH(a));
a||g.YG("yt-remote-cast-receiver");g.qG("yt-remote-cast2-session-change",a)}),g.qa("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
D8("cloudview.createSingleton_: "+c);return c},txa=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.cF||a},j9=function(a,b){L8()?E8().setConnectedScreenStatus(a,b):N8("setConnectedScreenStatus called before ready.")},uxa=function(){D8("clearCurrentReceiver");
g.YG("yt-remote-cast-receiver")},vxa=function(){if(Q8("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){mxa();a({command:"cast.sender.init"});return}}if(!window.chrome||Q8("Edge"))g.Gh();else if(mxa(),Q8("Android")&&Q8("Chrome/")&&window.navigator.presentation){var a="",b=g.Ch();55<=b?a="55":50<=b&&(a="50");g.Jh("//www.gstatic.com/eureka/clank"+a+g.Hh,g.Gh)}else g.Kh(0)},wxa=function(a){a?(g.WG("yt-remote-session-app",a.app),g.WG("yt-remote-session-name",a.name)):(g.YG("yt-remote-session-app"),g.YG("yt-remote-session-name"));
g.qa("yt.mdx.remote.channelParams_",a,void 0)},xxa=function(){var a=R8();
if(g.Ub(a)){var a=g.CH(),b=g.XG("yt-remote-session-name")||"",c=g.XG("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.qa("yt.mdx.remote.channelParams_",a,void 0)}},yxa=function(){var a=X8();
a?(Y8("Resume connection to: "+g.rH(a)),W8(a,0)):(g.KH(),uxa(),Y8("Skipping connecting because no session screen found."))},zxa=function(a){Y8("remote.onCastSessionChange_: "+g.rH(a));
if(a){var b=U8();b&&b.id==a.id?j9(b.id,"YouTube TV"):(b&&$8(),W8(a,1))}else F8()&&$8()},Axa=function(){var a=nxa(),b=U8();
b||(b=X8());return g.$a(a,function(a){return b&&g.oH(b,a.key)?!0:!1})},Bxa=function(){var a=g.XG("yt-remote-cast-receiver");
return a?a.friendlyName:null},Cxa=function(a,b,c,d,e){txa()?sxa(b,e)&&(K8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?ixa(a,c):(window.__onGCastApiAvailable=function(b,d){b?ixa(a,c):(N8("Failed to load cast API: "+d),M8(!1),K8(!1),g.YG("yt-remote-cast-available"),g.YG("yt-remote-cast-receiver"),dxa(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):kxa():vxa())):D8("Cannot initialize because not running Chrome")},
Dxa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.wg(a)||"";b&&(this.port=":"+b);this.domain=g.vg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ra(a,"10.0")&&(this.o=!1))},Exa=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
return c},k9=function(){var a=Axa();
!a&&O8()&&Bxa()&&(a={key:"cast-selector-receiver",name:Bxa()});return a},Fxa=function(){var a=nxa();
O8()&&g.XG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Gxa=function(a){var b={device:"Desktop",
app:"youtube-desktop"},b=g.XD("MDX_CONFIG")||b;g.UG&&Zwa();g.EH();V8||(V8=new Dxa(b?b.loungeApiHost:void 0),g.MH()&&(V8.g="/api/loungedev"));S8||(S8=g.v("yt.mdx.remote.deferredProxies_")||[],g.qa("yt.mdx.remote.deferredProxies_",S8,void 0));xxa();var c=J8();if(!c){var d=new g.XH(V8);g.qa("yt.mdx.remote.screenService_",d,void 0);c=J8();Cxa(a,d,function(a){a?H8()&&j9(H8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.qG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0)}b&&!g.v("yt.mdx.remote.initialized_")&&(g.qa("yt.mdx.remote.initialized_",!0,void 0),Y8("Initializing: "+g.ng(b)),l9.push(g.mG("yt-remote-cast2-availability-change",function(){g.qG("yt-remote-receiver-availability-change")})),l9.push(g.mG("yt-remote-cast2-receiver-selected",function(){G8(null);
g.qG("yt-remote-auto-connect","cast-selector-receiver")})),l9.push(g.mG("yt-remote-cast2-receiver-resumed",function(){g.qG("yt-remote-receiver-resumed","cast-selector-receiver")})),l9.push(g.mG("yt-remote-cast2-session-change",zxa)),l9.push(g.mG("yt-remote-connection-change",function(a){a?j9(H8(),"YouTube TV"):X8()||(j9(null,null),uxa())})),a=R8(),b.isAuto&&(a.id+="#dial"),g.iF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),Y8(" -- with channel params: "+
g.ng(a)),wxa(a),c.start(),H8()||yxa())},m9=function(){O8()?E8()?L8()?(D8("Requesting cast selector."),E8().requestSession()):(D8("Wait for cast API to be ready to request the session."),P8.push(g.mG("yt-remote-cast2-api-ready",m9))):N8("requestCastSelector: Cast is not initialized."):N8("requestCastSelector: Cast API is not installed!")},n9=function(a,b,c){g.K.call(this);
this.F=a;this.V=b;this.o=new g.XF(this);g.L(this,this.o);this.o.T(b,"onCaptionsTrackListChanged",this.dP);this.o.T(b,"captionschanged",this.PN);this.o.T(b,"captionssettingschanged",this.YB);this.o.T(b,"videoplayerreset",this.Yn);this.o.T(b,"mdxautoplaycancel",this.EG);this.O=this.o.T(b,"onVolumeChange",this.sA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.DA,this);c.subscribe("remotePlayerChange",this.kl,this);c.subscribe("remoteQueueChange",this.Yn,this);c.subscribe("autoplayUpNext",this.fA,
this);c.subscribe("previousNextChange",this.AA,this);c.subscribe("nowAutoplaying",this.tA,this);c.subscribe("autoplayDismissed",this.eA,this);this.suggestion=null;this.G=new g.eQ(64);this.A=new g.Ct(this.TB,500,this);g.L(this,this.A);this.B=new g.Ct(this.UB,1E3,this);g.L(this,this.B);this.C={};this.K=new g.Ct(this.lC,1E3,this);g.L(this,this.K);this.J=new g.jk(this.NL,1E3,this);g.L(this,this.J);this.M=g.x;this.YB();this.Yn();this.kl()},o9=function(a,b){var c=a.F,d=a.V.ha().lengthSeconds;
c.J=b||0;c.g.Y("progresssync",b,d)},Hxa=function(a){o9(a,0);
a.A.stop();p9(a,new g.eQ(64))},r9=function(a,b){if(q9(a)&&!a.D){var c=null;
b&&(c={style:a.V.oi()},g.$b(c,b));a.g.MB(a.V.ha().videoId,c);a.C=c9(a.g).o}},s9=function(a,b){var c=a.V.Pf();
c?pxa(a.g,a.V.ha().videoId,b,c.de(),c.listId.toString()):pxa(a.g,a.V.ha().videoId,b);p9(a,new g.eQ(1))},Ixa=function(a,b){if(b){var c=a.V.zc("captions","tracklist",{Vx:1});
c&&c.length?(a.V.Ed("captions","track",b),a.D=!1):(a.V.Qk("captions"),a.D=!0)}else a.V.Ed("captions","track",{})},q9=function(a){return c9(a.g).videoId==a.V.ha().videoId},p9=function(a,b){a.B.stop();
var c=a.G;if(!g.kQ(c,b)){var d=g.V(b,2);if(d!=g.V(a.G,2)){var e=a.V;g.Z1(e.app,d,e.playerType)}a.G=b;Jxa(a.F,c,b)}},t9=function(a){g.X.call(this,{H:"div",
N:"ytp-remote",L:[{H:"div",N:"ytp-remote-display-status",L:[{H:"div",N:"ytp-remote-display-status-icon",L:[g.bE()]},{H:"div",N:"ytp-remote-display-status-text",L:["{{statustext}}"]}]}]});this.o=new g.YV(this,250);g.L(this,this.o);this.A=a;this.T(a,"presentingplayerstatechange",this.B);Kxa(this,g.TU(a))},Kxa=function(a,b){if(3==a.A.Wa()){var c={RECEIVER_NAME:a.A.zc("remote","currentReceiver").name},c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.xb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Ha("statustext",c);a.o.show()}else a.o.hide()},u9=function(a){g.LV.call(this,a);
this.A={key:g.tH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.K=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.eQ(64);this.J=0;var b=g.MU(a).D;b&&(b=b.A&&b.A.g)&&(b=new B8(a,b),g.L(this,b));b=new t9(a);g.L(this,b);g.nV(a,b.element,4)},Jxa=function(a,b,c){a.F=c;
a.g.Y("presentingplayerstatechange",new g.pQ(c,b))},v9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)$8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ha().videoId;if(c||d){var e=a.g.Pf();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.gc(k).videoId}else f=[a.g.ha().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Jy(),0),currentTime:a.g.getCurrentTime()}}else c=null;Y8("Connecting to: "+g.ng(b));"cast-selector-receiver"==b.key?(G8(c||null),c=c||null,L8()?E8().setLaunchParams(c):N8("setLaunchParams called before ready.")):!c&&Z8()&&H8()==b.key?g.qG("yt-remote-connection-change",!0):
($8(),G8(c||null),c=J8().fe(),(c=g.vH(c,b.key))&&W8(c,1))}};
g.p(B8,g.a1);B8.prototype.J=function(){var a=this.V.zc("remote","receivers");a&&1<a.length&&!this.V.zc("remote","quickCast")?(this.F=g.Db(a,this.B,this),g.c1(this,(0,g.H)(a,this.B)),a=this.V.zc("remote","currentReceiver"),g.b1(this,this.B(a)),this.enable(!0)):this.enable(!1)};
B8.prototype.B=function(a){return a.key};
B8.prototype.pf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
B8.prototype.sd=function(a){g.a1.prototype.sd.call(this,a);this.V.Ed("remote","currentReceiver",this.F[a]);this.A.Vb()};
g.z(C8,g.wH);g.h=C8.prototype;g.h.fe=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.Vo=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Eo=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.cd.$_ubk(this.o[a]);this.o.length=0;this.cd=null;C8.aa.X.call(this)};
g.h.xT=function(){this.Y("screenChange")};
g.h.JP=function(){this.Y("onlineScreenChange")};
var I8=null,P8=[],S8=null,V8=null;g.z(b9,g.$F);g.h=b9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,i9(this,"play")):d9(this,"play"),g9(this,1,g.tI(c9(this))),this.Y("remotePlayerChange")):f9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,i9(this,"pause")):d9(this,"pause"),g9(this,2,g.tI(c9(this))),this.Y("remotePlayerChange")):f9(this,this.pause)};
g.h.yC=function(a){if(1==this.g){if(this.o){var b=c9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.xb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,i9(this,"seekTo",{newTime:a}))}else d9(this,"seekTo",{newTime:a});g9(this,3,a);this.Y("remotePlayerChange")}else f9(this,g.za(this.yC,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,i9(this,"stopVideo")):d9(this,"stopVideo");var a=c9(this);a.index=-1;a.videoId="";g.rI(a);e9(this,a);this.Y("remotePlayerChange")}else f9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=c9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.y)(function(){h9("set receiver volume: "+d)},this),(0,g.y)(function(){this.jc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.y)(function(){h9("set receiver muted: "+b)},this),(0,g.y)(function(){this.jc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d9(this,"setVolume",e)}c.muted=b;c.volume=a;e9(this,c)}else f9(this,g.za(this.setVolume,a,b))};
g.h.MB=function(a,b){if(1==this.g){var c=c9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ng(b.style),g.$b(d,c.o));d9(this,"setSubtitlesTrack",d);e9(this,c)}else f9(this,g.za(this.MB,a,b))};
g.h.Xt=function(a,b){if(1==this.g){d9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Tc.id});var c=c9(this);c.audioTrackId=b.Tc.id;e9(this,c)}else f9(this,g.za(this.Xt,a,b))};
g.h.xC=function(a,b){if(1==this.g){if(a&&b){var c=c9(this);g.uI(c,a,b);e9(this,c)}d9(this,"previous")}else f9(this,g.za(this.xC,a,b))};
g.h.wC=function(a,b){if(1==this.g){if(a&&b){var c=c9(this);g.uI(c,a,b);e9(this,c)}d9(this,"next")}else f9(this,g.za(this.wC,a,b))};
g.h.tw=function(){1==this.g?d9(this,"dismissAutoplay"):f9(this,this.tw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.Y("proxyStateChange",a,this.g)}b9.aa.dispose.call(this)};
g.h.X=function(){qxa(this);this.B=null;this.C.clear();a9(this,null);b9.aa.X.call(this)};
g.h.Yt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.Y("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.NB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.aQ=function(a,b){this.Y(a,b)};
g.h.RN=function(a){if(!a)this.fl(null),a9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=c9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)h9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,e9(this,b)}};
g.h.fl=function(a){h9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),rxa(this),this.Y("remotePlayerChange")};
g.h.QN=function(a){a?(rxa(this),this.Y("remotePlayerChange")):this.fl(null)};
g.h.eO=function(){var a=jxa();a&&a9(this,a)};
g.h.jc=function(a){g.jH("CP",a)};
var l9=[];g.h=Dxa.prototype;g.h.Zh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Dg(b+a,{})};
g.h.Wt=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Lb:g.za(this.sT,c,!0),onError:g.za(this.rT,d),fd:g.za(this.tT,d)};b&&(c.Pb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.UE(a,c)};
g.h.sT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.rT=function(a,b){a(Error("Request error: "+b.status))};
g.h.tT=function(a){a(Error("request timed out"))};g.p(n9,g.K);g.h=n9.prototype;g.h.X=function(){g.K.prototype.X.call(this);this.A.stop();this.B.stop();this.M();this.g.unsubscribe("proxyStateChange",this.DA,this);this.g.unsubscribe("remotePlayerChange",this.kl,this);this.g.unsubscribe("remoteQueueChange",this.Yn,this);this.g.unsubscribe("autoplayUpNext",this.fA,this);this.g.unsubscribe("previousNextChange",this.AA,this);this.g.unsubscribe("nowAutoplaying",this.tA,this);this.g.unsubscribe("autoplayDismissed",this.eA,this);this.g=this.F=null};
g.h.hz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(q9(this)){if(1081!=c9(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":c9(this.g).xb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.cj(c[0],c[1]);break;case "control_subtitles_set_track":r9(this,c[0]);break;case "control_set_audio_track":c=c[0],q9(this)&&this.g.Xt(this.V.ha().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":s9(this,this.V.getCurrentTime());break;case "control_seek":s9(this,c[0]);break;case "control_subtitles_set_track":r9(this,c[0]);break;case "control_set_audio_track":c=c[0],q9(this)&&this.g.Xt(this.V.ha().videoId,c)}};
g.h.PN=function(a){this.hz("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.YB=function(){var a=this.V.zc("captions","track");g.Ub(a)||r9(this,a)};
g.h.sA=function(a){if(q9(this)){this.g.unsubscribe("remotePlayerChange",this.kl,this);var b=Math.round(a.volume);a=!!a.muted;var c=c9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.kl,this)}};
g.h.dP=function(){g.Ub(this.C)||Ixa(this,this.C);this.D=!1};
g.h.DA=function(a,b){this.B.stop();2==b&&this.UB()};
g.h.kl=function(){if(q9(this)){this.A.stop();var a=c9(this.g);switch(a.g){case 1081:p9(this,new g.eQ(8));break;case 1:this.TB();p9(this,new g.eQ(8));break;case 1083:case 3:p9(this,new g.eQ(9));break;case 0:p9(this,new g.eQ(2));this.J.stop();o9(this,this.V.ha().lengthSeconds);break;case 1082:p9(this,new g.eQ(4));break;case 2:p9(this,new g.eQ(4));o9(this,g.tI(a));break;case -1:p9(this,new g.eQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},p9(this,new g.eQ(128,
a))}var a=c9(this.g).o,b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,Ixa(this,a));a=c9(this.g);-1==a.volume||Math.round(this.V.getVolume())==a.volume&&this.V.Me()==a.muted||this.K.isActive()||this.lC()}else Hxa(this)};
g.h.AA=function(){this.V.Y("mdxpreviousnextchange")};
g.h.Yn=function(){q9(this)||Hxa(this)};
g.h.EG=function(){this.g.tw()};
g.h.fA=function(a){a&&(a=g.UE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Lb:(0,g.y)(this.bR,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.bR=function(a,b){var c=new g.tP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.V.Y("mdxautoplayupnext",c)};
g.h.tA=function(a){(0,window.isNaN)(a)||this.V.Y("mdxnowautoplaying",a)};
g.h.eA=function(){this.V.Y("mdxautoplaycanceled")};
g.h.NL=function(a,b){-1==c9(this.g).g?s9(this,a):b&&this.g.yC(a)};
g.h.lC=function(){if(q9(this)){var a=c9(this.g);this.o.Ca(this.O);a.muted?this.V.mute():this.V.Sf();this.V.setVolume(a.volume);this.O=this.o.T(this.V,"onVolumeChange",this.sA)}};
g.h.TB=function(){this.A.stop();if(!this.g.oa()){var a=c9(this.g);a.xb()&&p9(this,new g.eQ(8));o9(this,g.tI(a));this.A.start()}};
g.h.UB=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(t9,g.X);t9.prototype.B=function(a){Kxa(this,a.state)};g.p(u9,g.LV);g.h=u9.prototype;g.h.create=function(){Gxa("embedded"==g.W(this.g).g);this.D.push(g.mG("yt-remote-before-disconnect",this.MN,this));this.D.push(g.mG("yt-remote-connection-change",this.kQ,this));this.D.push(g.mG("yt-remote-receiver-availability-change",this.BA,this));this.D.push(g.mG("yt-remote-auto-connect",this.iQ,this));this.D.push(g.mG("yt-remote-receiver-resumed",this.hQ,this));this.BA()};
g.h.load=function(){this.g.Pp();g.LV.prototype.load.call(this);this.C=new n9(this,this.g,this.o);var a=hxa(),a=a?a.currentTime:0,b=Z8()?new b9(F8(),void 0):null;0==a&&b&&(a=g.tI(c9(b)));0!=a&&(this.J=a||0,this.g.Y("progresssync",a,void 0));Jxa(this,this.F,this.F);g.d2(this.g.app,6)};
g.h.unload=function(){this.g.Y("mdxautoplaycanceled");this.B=this.A;g.Oe(this.C,this.o);this.o=this.C=null;g.LV.prototype.unload.call(this);g.d2(this.g.app,5)};
g.h.X=function(){g.nG(this.D);g.LV.prototype.X.call(this)};
g.h.Vk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.hz.apply(this.C,[].concat([a],c instanceof Array?c:Exa(g.ia(c))))};
g.h.qH=function(){return this.loaded?this.C.suggestion:null};
g.h.Jf=function(){return this.o?c9(this.o).Jf:!1};
g.h.hasNext=function(){return this.o?c9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.sL=function(){var a=c9(this.o),b=this.g.ha();return{allowSeeking:this.g.Pd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.F)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.F)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+((0,g.F)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.F)()-a.A)/1E3:a.D}};
g.h.tL=function(){this.o&&this.o.wC()};
g.h.uL=function(){this.o&&this.o.xC()};
g.h.MN=function(a){1==a&&(this.K=this.o?c9(this.o):null)};
g.h.kQ=function(){var a=Z8()?new b9(F8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ne(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.ha().videoId&&this.g.Hy(a.videoId,g.tI(a)));this.g.Y("videodatachange","newdata",this.g.ha(),3)};
g.h.BA=function(){this.G=[this.A].concat(Fxa());var a=k9()||this.A;v9(this,a);this.g.ya("onMdxReceiversChange")};
g.h.iQ=function(){var a=k9();v9(this,a)};
g.h.hQ=function(){this.B=k9()};
g.h.rL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?m9():v9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&m9(),!0):!1}};
g.h.vL=function(){d9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Gd=function(){return!1};g.cW("remote",u9);})(_yt_player);
